id: P1E133EF4
initial_creation_type: ocr
source_metadata:
  volumes:
    863f111a26ce4a6598f775484a7660fd:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: འཇམ་པ་ཁྲོ་བོར་སྒྲུབ་པ།
      total_pages: 1902
      volume_number: 26
